### ISSUE TITLE
Handling 412 errors (empty change, object was not modified)

### ISSUE THREAD

**Issue by nickdaugherty** [Automattic/node-simperium#1]
Currently, if we attempt to update an object that results in a no-change (identical objects), an unhandled error is thrown because the module treats `412` errors as real errors.

In Simperium, a `412` is:

> 412 — empty change, object was not modified

not really an error, more a warning. This condition causes this uncaught error to be thrown:

```
node_modules/simperium/node_modules/node-promise/promise.js:204
          throw error;
                ^
Error: Could not apply change to 
    at Channel.private.applyChange (node_modules/simperium/lib/simperium/channel.js:471:17)
    at Channel.<anonymous> (node_modules/simperium/lib/simperium/util/fn.js:57:15)
    at Object._onImmediate (node_modules/simperium/node_modules/node-promise/promise.js:164:27)
    at processImmediate [as _immediateCallback] (timers.js:330:15)
```

**Comment by nickdaugherty** [comment]
This could be solved by either not emitting an error for 412's in Channel.js, or making the Channel of a bucket accessible to outside code, so that an error handler could be added there.

Thoughts @beaucollins? We may want to do both - set a `channel` property of the bucket in the `Client.bucket()` method, which would give access to error events on the Channel, and then gracefully handle 412's as not _real_ errors.

**Comment by beaucollins** [comment]
The remedy here is to not emit error on a 412. Error handling is absent at the moment.

I'll dive in.

**Comment by beaucollins** [comment]
Another change is to not send a change when an object diff is empty.
